[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "van-rally"
version = "0.1.0"
description = "Roadsurfer Van-Rally Routes Checker"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "PyYAML>=6.0.3",
]

[project.scripts]
van-rally = "van_rally.main:main"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.setuptools.package-data]
van_rally = ["translations/*.json", "config.example.yaml"]

[project.optional-dependencies]
dev = [
    "build",
    "ruff>=0.16.8,<0.17",
    "pytest",
    "pytest-mock",
    "pytest-cov",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
addopts = "-v --strict-markers"
